# Generated by Django 4.2.7 on 2024-08-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_list',
            fields=[
                ('stock_ticker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=255)),
                ('state', models.BooleanField()),
                ('stock_parameters', models.CharField(max_length=255)),
            ],
        ),
    ]
